steps:
  # Build Docker image with Shopify credentials directly
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '--build-arg',
        'SHOPIFY_STORE_DOMAIN=$$SHOPIFY_STORE_DOMAIN',
        '--build-arg',
        'SHOPIFY_STOREFRONT_ACCESS_TOKEN=$$SHOPIFY_STOREFRONT_ACCESS_TOKEN',
        '-t',
        'gcr.io/$PROJECT_ID/izerwaren-revival:$BUILD_ID',
        '-t',
        'gcr.io/$PROJECT_ID/izerwaren-revival:latest',
        '.',
      ]
    secretEnv: ['SHOPIFY_STORE_DOMAIN', 'SHOPIFY_STOREFRONT_ACCESS_TOKEN']

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/izerwaren-revival:$BUILD_ID']

  # Deploy to Cloud Run (blue/green via script)
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args: ['./scripts/deploy-blue-green.sh']
    env:
      - 'PROJECT_ID=$PROJECT_ID'
      - 'IMAGE_URL=gcr.io/$PROJECT_ID/izerwaren-revival:$BUILD_ID'
      - 'SERVICE_NAME=izerwaren-revival'
      - 'REGION=us-central1'

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'

timeout: '1200s'

# Secret Manager configuration
availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/shopify-store-domain/versions/latest
      env: 'SHOPIFY_STORE_DOMAIN'
    - versionName: projects/$PROJECT_ID/secrets/shopify-storefront-token/versions/latest
      env: 'SHOPIFY_STOREFRONT_ACCESS_TOKEN'
