# Development overrides for docker-compose.yml
# This file is automatically loaded by docker-compose and provides development-specific configurations

services:
  # Development-specific backend configuration
  backend:
    environment:
      NODE_ENV: development
      DEBUG: "izerwaren:*"
    volumes:
      # Additional development volumes
      - ./scripts:/app/scripts
      - ./.env:/app/.env:ro
    # Enable debugging
    ports:
      - "9229:9229" # Node.js debugging port
    command: ["sh", "-c", "npm run db:migrate && npm run db:seed && npm run backend:dev"]

  # Development-specific frontend configuration
  frontend:
    environment:
      NODE_ENV: development
      # Enable Next.js fast refresh
      FAST_REFRESH: true
      # Disable telemetry in development
      NEXT_TELEMETRY_DISABLED: 1
    volumes:
      # Mount environment file for hot reload
      - ./.env:/app/.env:ro
      - ./.env.local:/app/.env.local:ro

  # Development database with additional tools
  database:
    ports:
      - "5432:5432"
    environment:
      # Enable additional logging for development
      POSTGRES_LOG_STATEMENT: all
      POSTGRES_LOG_MIN_DURATION_STATEMENT: 0
    volumes:
      # Mount additional development scripts
      - ./scripts/dev-db-setup.sql:/docker-entrypoint-initdb.d/dev-setup.sql:ro
