version: '3.8'

services:
  shopify-demo:
    build:
      context: .
      dockerfile: Dockerfile.simple
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: unless-stopped
